---
- name: Update apt repo and cache (Ubuntu)
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Java (Ubuntu)
  apt:
    name: openjdk-17-jdk
    state: present
  when: ansible_os_family == 'Debian'
  